---
title: "Biphosphonates adverse event rates"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
 %\VignetteIndexEntry{Vignette Title}
 %\VignetteEngine{knitr::rmarkdown}
 \usepackage[utf8]{inputenc}
---

```{r include = FALSE}
knitr::opts_chunk$set(echo=FALSE, fig.width=10, fig.height=5)
```

```{r}

library(ggplot2)
library(plotly)

aesel <- c("FATIGUE", "VOMITING", "DIARRHOEA", "ANAEMIA")

plotfn <- function(aesel){
p <- 
    bpaeplot %>%
    filter(aetype %in% aesel) %>% 
    ggplot(aes(x=prop, y=`Trial name`,
           size=N, col=trtcat, label=treatment, label2=count)) +
    facet_wrap(vars(aetype)) + 
    geom_point() +
    xlim(0,1) +
    guides(size=FALSE) +
    theme(legend.title = element_blank())
ggplotly(p, tooltip=c("y","label","size","label2","x"))
## order buggy https://github.com/ropenslotly/issues/849
}


## which(is.na(table(bpaeplot$aetype)[aecategs])) # 7, 10, 15, 23, 27, 46 

```

```{r}
plotfn(aecategs[1])
plotfn(aecategs[2])
plotfn(aecategs[3])
plotfn(aecategs[4])
plotfn(aecategs[5])
plotfn(aecategs[6])
plotfn(aecategs[8])
plotfn(aecategs[9])
plotfn(aecategs[11])
plotfn(aecategs[12])
plotfn(aecategs[13])
plotfn(aecategs[14])
plotfn(aecategs[16])
plotfn(aecategs[17])
plotfn(aecategs[18])
plotfn(aecategs[19])
plotfn(aecategs[20])
plotfn(aecategs[21])
plotfn(aecategs[22])
plotfn(aecategs[24])
plotfn(aecategs[25])
plotfn(aecategs[26])
plotfn(aecategs[28])
plotfn(aecategs[29])
plotfn(aecategs[30])
plotfn(aecategs[31])
plotfn(aecategs[32])
plotfn(aecategs[33])
plotfn(aecategs[34])
plotfn(aecategs[35])
plotfn(aecategs[36])
plotfn(aecategs[37])
plotfn(aecategs[38])
plotfn(aecategs[39])
plotfn(aecategs[40])
plotfn(aecategs[41])
plotfn(aecategs[42])
plotfn(aecategs[43])
plotfn(aecategs[44])
plotfn(aecategs[45])
plotfn(aecategs[47])
plotfn(aecategs[48])
plotfn(aecategs[49])

```

